[[constraint]]
  branch = "master"
  name = "github.com/mdwhatcott/advent-of-code"

[[constraint]]
  name = "github.com/smartystreets/assertions"
  version = "1.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/smartystreets/gunit"
